services:
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    pid: host
    volumes:
      - "/:/host:ro"
        
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports: 
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
        
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "5000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234 
      MYSQL_DATABASE: messages
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app_network
  
volumes:
  db_data:
  
networks:
  app_network:
    driver: bridge