CREATE DATABASE IF NOT EXISTS messages;

USE messages;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Sender VARCHAR(100) NOT NULL,
    Content VARCHAR(600) NOT NULL,
    SentTime TIMESTAMP
);