global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "MyASPNETApp"
    scrape_interval: 5s
    static_configs:
      - targets: ['fyp-load-balancer-ehhxd7c7csbrbpb3.northeurope-01.azurewebsites.net']
    
    metrics_path: /metrics/
    scheme: https